name = "ufukty.com"
compatibility_date = "2025-12-06"
preview_urls = true

[build]
command = "npm run build"

[assets]
directory = "./build"
html_handling = "none"
not_found_handling = "none"

[[routes]]
pattern = "ufukty.com"
zone_name = "ufukty.com"
custom_domain = true