name = "ufukty"
compatibility_date = "2025-12-06"
workers_dev = true
preview_urls = true

[assets]
directory = "./public"
html_handling = "none"
not_found_handling = "none"

[[routes]]
pattern = "ufukty.com"
zone_name = "ufukty.com"
custom_domain = true
