name = "ufukty"
main = "worker/index.ts"
compatibility_date = "2025-12-06"
preview_urls = true

[assets]
binding = "ASSETS"
directory = "./public"
html_handling = "none"
not_found_handling = "none"

[[routes]]
pattern = "ufukty.com"
zone_name = "ufukty.com"
custom_domain = true
